name: Daily Script Execution

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run cleaner.py
      run: python cleaner.py

    - name: Commit and push changes from cleaner.py
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add articles.json summaries.json
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Mise à jour des fichiers articles.json et summaries.json après exécution de cleaner.py"
          git pull --rebase
          git push
        fi

    - name: Run scraper.py
      run: python scraper.py

    - name: Commit and push changes from scraper.py
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add articles.json
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Mise à jour du fichier articles.json après exécution de scraper.py"
          git pull --rebase
          git push
        fi

    - name: Run sum.py
      run: python sum.py

    - name: Commit and push changes from sum.py
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add summaries.json
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Mise à jour du fichier summaries.json après exécution de sum.py"
          git pull --rebase
          git push
        fi

    - name: Run sorter.py
      run: python sorter.py

    - name: Commit and push changes from sorter.py
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add sorted_summaries.json
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Mise à jour du fichier sorted_summaries.json après exécution de sorter.py"
          git pull --rebase
          git push
        fi
