name: Daily Script Execution

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r .github/requirements.txt  # Assurez-vous d'avoir un fichier requirements.txt s'il y a des dépendances à installer

    - name: Run Python script
      run: python .github/frandroid.py  # Remplacez path/to/your/script.py par le chemin vers votre script Python

    - name: Commit et push des modifications
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .github/articles_after_date.json
        git commit -m "Mise à jour du fichier JSON"
        git push
