name: Daily Script Execution

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run cleaner script
      run: python cleaner.py

    - name: Commit changes after cleaner
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git pull origin main
        git add articles.json summaries.json
        if git diff --cached --quiet; then
          echo "No changes to commit after cleaner."
        else
          git commit -m "Cleaned old articles and summaries"
          git push origin main
        fi

    - name: Run scrapper script
      run: python scraper.py

    - name: Commit changes after scrapper
      run: |
        git pull origin main
        git add articles.json
        if git diff --cached --quiet; then
          echo "No changes to commit after scrapper."
        else
          git commit -m "Scraped new articles"
          git push origin main
        fi

    - name: Run summarizer script
      run: python sum.py

    - name: Commit changes after summarizer
      run: |
        git pull origin main
        git add summaries.json
        if git diff --cached --quiet; then
          echo "No changes to commit after summarizer."
        else
          git commit -m "Added summaries"
          git push origin main
        fi

    - name: Run sorter script
      run: python sorter.py

    - name: Commit changes after sorter
      run: |
        git pull origin main
        git add sorted_summaries.json
        if git diff --cached --quiet; then
          echo "No changes to commit after sorter."
        else
          git commit -m "Sorted summaries"
          git push origin main
        fi
